name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Install Compose
      #   run: |
      #     curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      #     sudo chmod +x /usr/local/bin/docker-compose
      # - name: Build the Docker image
      #   run: docker-compose -f build/docker-compose.yaml build builder
      # - name: Build binaries
      #   run: docker-compose -f build/docker-compose.yaml run --rm builder build -f build/goreleaser.yml --rm-dist --snapshot --id linux --id windows
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: Build Linux AMD64 and Windows
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build -f build/goreleaser.yml --rm-dist --snapshot --id linux-amd --id windows

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build in VM
        uses: uraimo/run-on-arch-action@v2
        id: build
        with:
          arch: aarch64
          distro: none
          base_image: goreleaser/goreleaser-cross:v1.19
          run: |
              apt-get update && apt-get install -y gcc libgtk-3-dev libayatana-appindicator3-dev wget
              # golang
              # wget https://go.dev/dl/go1.19.5.linux-arm64.tar.gz
              # sudo tar -C /usr/local -xzf go1.19.5.linux-arm64.tar.gz
              # export PATH=$PATH:/usr/local/go/bin
              # goreleaser
              # go install github.com/goreleaser/goreleaser@latest
              goreleaser build -f build/goreleaser.yml --rm-dist --snapshot --id linux-arm
