name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Install Compose
      #   run: |
      #     curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      #     sudo chmod +x /usr/local/bin/docker-compose
      # - name: Build the Docker image
      #   run: docker-compose -f build/docker-compose.yaml build builder
      # - name: Build binaries
      #   run: docker-compose -f build/docker-compose.yaml run --rm builder build -f build/goreleaser.yml --rm-dist --snapshot --id linux --id windows
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev
          curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: Build Linux AMD64 and Windows
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build -f build/goreleaser.yml --rm-dist --snapshot --id linux-amd --id windows
      - name: Build the Docker image
        run: docker-compose -f build/docker-compose.yaml build builder
      - name: Build Linux ARM64
        run:docker-compose -f build/docker-compose.yaml run --rm builder build -f build/goreleaser.yml --rm-dist --snapshot --id linux-arm
